package com.sg.guessnum.dto;

public class Game
{
    //Database primary key Id ( autogenerated and incremented by database ).
    private int gameId;

    //Numbers that represent the answer when combined.
    private int thousands;
    private int hundreds;
    private int tens;
    private int units;
    private int answer;

    private boolean finished;

    public Game()
    {
    }

    public Game( int thousands, int hundreds, int tens, int units )
    {
        this.thousands = thousands;
        this.hundreds = hundreds;
        this.tens = tens;
        this.units = units;
        this.answer = units + (tens * 10) + (hundreds * 100) + (thousands * 1000);

        this.finished = false;
    }

    public int getGameId()
    {
        return gameId;
    }

    public void setGameId( int gameId )
    {
        this.gameId = gameId;
    }

    public int getThousands()
    {
        return thousands;
    }

    public void setThousands( int thousands )
    {
        this.thousands = thousands;
    }

    public int getHundreds()
    {
        return hundreds;
    }

    public void setHundreds( int hundreds )
    {
        this.hundreds = hundreds;
    }

    public int getTens()
    {
        return tens;
    }

    public void setTens( int tens )
    {
        this.tens = tens;
    }

    public int getUnits()
    {
        return units;
    }

    public int getAnswer()
    {
        return answer;
    }

    public void setAnswer()
    {
        this.answer = units + (tens * 10) + (hundreds * 100) + (thousands * 1000);
    }

    public void setAnswer( int answer )
    {
        this.answer = answer;
    }

    public void setUnits( int units )
    {
        this.units = units;
    }

    public boolean isFinished()
    {
        return finished;
    }

    public void setFinished( boolean finished )
    {
        this.finished = finished;
    }
}
